/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description No SQL, no model call, no business validation here -- everything
         *     below Query()'s own type/range constraints (empty/whitespace-only
         *     query, year_from > year_to) is handled by search_papers() itself and
         *     surfaces as a ValueError, mapped to 400 by the registered handler.
         */
        get: operations["search_api_v1_papers_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paper Detail
         * @description Declared AFTER /search: a path param without an explicit :type
         *     converter in the path string (e.g. "{paper_id}") matches ANY string at
         *     the routing level -- "search" would otherwise match this route first
         *     and fail UUID coercion (422) before ever reaching the real /search
         *     handler, the same class of ordering hazard as /clusters/noise vs
         *     /clusters/{cluster_id}. Shape doesn't collide with /{paper_id}/similar
         *     (different segment count), so this route's position relative to that
         *     one doesn't matter.
         */
        get: operations["paper_detail_api_v1_papers__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Similar
         * @description paper_id: uuid.UUID as the path type means a malformed UUID never
         *     reaches this function body -- FastAPI rejects it with 422 first.
         */
        get: operations["similar_api_v1_papers__paper_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/noise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Noise Papers */
        get: operations["noise_papers_api_v1_clusters_noise_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clusters */
        get: operations["list_clusters_api_v1_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{cluster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cluster Detail */
        get: operations["cluster_detail_api_v1_clusters__cluster_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{cluster_id}/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cluster Papers */
        get: operations["cluster_papers_api_v1_clusters__cluster_id__papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories */
        get: operations["categories_api_v1_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CategoryDistributionItem */
        CategoryDistributionItem: {
            /** Category */
            category: string;
            /** Count */
            count: number;
            /** Percent */
            percent: number;
        };
        /** CategoryListResponse */
        CategoryListResponse: {
            /** Count */
            count: number;
            /** Categories */
            categories: components["schemas"]["CategorySummary"][];
        };
        /** CategorySummary */
        CategorySummary: {
            /** Code */
            code: string;
            /** Display Name */
            display_name: string;
            /** Paper Count */
            paper_count: number;
        };
        /** ClusterDetail */
        ClusterDetail: {
            /** Cluster Id */
            cluster_id: number;
            /** Cluster Name */
            cluster_name: string;
            /** Short Description */
            short_description: string;
            /** Paper Count */
            paper_count: number;
            /** Label Confidence */
            label_confidence: number;
            /** Keywords */
            keywords: string[];
            /** Evidence */
            evidence: components["schemas"]["ClusterEvidenceItem"][];
            /** Category Distribution */
            category_distribution: components["schemas"]["CategoryDistributionItem"][];
            /** Average Membership Probability */
            average_membership_probability: number;
            /** Representative Papers */
            representative_papers: components["schemas"]["RepresentativePaper"][];
            /** Clustering Run Id */
            clustering_run_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reviewed By */
            reviewed_by: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
        };
        /** ClusterEvidenceItem */
        ClusterEvidenceItem: {
            /** Paper Id */
            paper_id: string;
            /** Reason */
            reason: string;
        };
        /** ClusterListResponse */
        ClusterListResponse: {
            /** Clustering Run Id */
            clustering_run_id: string | null;
            /** Count */
            count: number;
            /** Clusters */
            clusters: components["schemas"]["ClusterSummary"][];
        };
        /**
         * ClusterPaper
         * @description Shared by /clusters/{id}/papers and /clusters/noise. Distinct from
         *     embeddings.PaperResult (search/similar-papers) on purpose: this carries
         *     membership_probability (confidence a PAPER belongs to its cluster) and
         *     is_noise, neither of which is a similarity_score -- the two concepts
         *     are never conflated under one "confidence" field anywhere in this API.
         */
        ClusterPaper: {
            /** Paper Id */
            paper_id: string;
            /** Arxiv Id */
            arxiv_id: string | null;
            /** Title */
            title: string;
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Primary Category */
            primary_category: string;
            /** Publication Date */
            publication_date: string | null;
            /** Membership Probability */
            membership_probability: number;
            /** Is Noise */
            is_noise: boolean;
        };
        /** ClusterPapersResponse */
        ClusterPapersResponse: {
            /** Cluster Id */
            cluster_id: number;
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Papers */
            papers: components["schemas"]["ClusterPaper"][];
        };
        /** ClusterSummary */
        ClusterSummary: {
            /** Cluster Id */
            cluster_id: number;
            /** Cluster Name */
            cluster_name: string;
            /** Short Description */
            short_description: string;
            /** Paper Count */
            paper_count: number;
            /** Label Confidence */
            label_confidence: number;
            /** Top Keywords */
            top_keywords: string[];
            /** Dominant Category */
            dominant_category: string | null;
            /** Average Membership Probability */
            average_membership_probability: number;
            /** Clustering Run Id */
            clustering_run_id: string;
        };
        /**
         * ErrorResponse
         * @description Matches the exact JSON shape every registered exception handler in
         *     exceptions.py already returns ({"detail": str(exc)}) -- this schema
         *     documents existing behavior, it does not change it.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Shared shape for both outcomes of GET /health -- only the values of
         *     status/database differ ("healthy"/"connected" vs "unhealthy"/
         *     "disconnected"), documented here for both the 200 and 503 responses
         *     rather than leaving 200 undocumented while only 503 has a real schema.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /** NoisePapersResponse */
        NoisePapersResponse: {
            /** Clustering Run Id */
            clustering_run_id: string | null;
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Papers */
            papers: components["schemas"]["ClusterPaper"][];
        };
        /**
         * PaperDetail
         * @description GET /papers/{paper_id}. Distinct from PaperResult -- this is a direct
         *     single-paper lookup, not a ranked search/similarity result, so it has no
         *     similarity_score and instead carries current_version_number and
         *     embedding_available (whether similar_papers() could use this paper as a
         *     source right now).
         */
        PaperDetail: {
            /** Paper Id */
            paper_id: string;
            /** Arxiv Id */
            arxiv_id: string | null;
            /** Title */
            title: string;
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Primary Category */
            primary_category: string;
            /** Publication Date */
            publication_date: string | null;
            /** Current Version Number */
            current_version_number: number;
            /** Embedding Available */
            embedding_available: boolean;
        };
        /**
         * PaperResult
         * @description One ranked result, shared by /search and /{paper_id}/similar. Field
         *     names/types map 1:1 onto the dicts search_papers()/similar_papers()
         *     already return.
         */
        PaperResult: {
            /** Paper Id */
            paper_id: string;
            /** Arxiv Id */
            arxiv_id: string | null;
            /** Title */
            title: string;
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Primary Category */
            primary_category: string;
            /** Publication Date */
            publication_date: string | null;
            /** Similarity Score */
            similarity_score: number;
        };
        /** PlatformOverview */
        PlatformOverview: {
            /** Total Canonical Papers */
            total_canonical_papers: number;
            /** Embedded Papers */
            embedded_papers: number;
            /** Approved Clusters */
            approved_clusters: number;
            /** Clustered Papers */
            clustered_papers: number;
            /** Noise Papers */
            noise_papers: number;
            /** Latest Clustering Run Id */
            latest_clustering_run_id: string | null;
            /** Database Status */
            database_status: string;
        };
        /** RepresentativePaper */
        RepresentativePaper: {
            /** Paper Id */
            paper_id: string;
            /** Arxiv Id */
            arxiv_id: string | null;
            /** Title */
            title: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Count */
            count: number;
            /** Results */
            results: components["schemas"]["PaperResult"][];
        };
        /** SimilarPapersResponse */
        SimilarPapersResponse: {
            /** Source Paper Id */
            source_paper_id: string;
            /** Count */
            count: number;
            /** Results */
            results: components["schemas"]["PaperResult"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is running and the database is reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description API is running but the database is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    search_api_v1_papers_search_get: {
        parameters: {
            query: {
                query: string;
                top_k?: number;
                category?: string | null;
                year_from?: number | null;
                year_to?: number | null;
                min_similarity?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_detail_api_v1_papers__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
            /** @description Paper not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_api_v1_papers__paper_id__similar_get: {
        parameters: {
            query?: {
                top_k?: number;
                category?: string | null;
                year_from?: number | null;
                year_to?: number | null;
                min_similarity?: number | null;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarPapersResponse"];
                };
            };
            /** @description Paper not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    noise_papers_api_v1_clusters_noise_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoisePapersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clusters_api_v1_clusters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterListResponse"];
                };
            };
        };
    };
    cluster_detail_api_v1_clusters__cluster_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cluster_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterDetail"];
                };
            };
            /** @description Cluster not found or approved label unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cluster_papers_api_v1_clusters__cluster_id__papers_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                category?: string | null;
                min_membership_probability?: number | null;
            };
            header?: never;
            path: {
                cluster_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterPapersResponse"];
                };
            };
            /** @description Cluster not found or approved label unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_v1_stats_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformOverview"];
                };
            };
        };
    };
    categories_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListResponse"];
                };
            };
        };
    };
}
