"""add cluster labels table

Revision ID: 04d1988e2686
Revises: 7d721ff30378
Create Date: 2026-07-30 09:32:55.473340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04d1988e2686'
down_revision: Union[str, None] = '7d721ff30378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clustering_run_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('cluster_name', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('generation_status', sa.Text(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('review_status', sa.Text(), server_default=sa.text("'PENDING_REVIEW'"), nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("generation_status <> 'SUCCEEDED' OR cluster_name IS NOT NULL", name='ck_cluster_labels_succeeded_has_name'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_cluster_labels_confidence_range'),
    sa.ForeignKeyConstraint(['clustering_run_id'], ['clustering_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clustering_run_id', 'cluster_id', 'provider', 'model', 'model_version', 'prompt_version', name='uq_cluster_labels_identity')
    )
    op.create_index('ix_cluster_labels_run_cluster', 'cluster_labels', ['clustering_run_id', 'cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cluster_labels_run_cluster', table_name='cluster_labels')
    op.drop_table('cluster_labels')
    # ### end Alembic commands ###
