"""baseline schema

Revision ID: 540c5f408063
Revises: 
Create Date: 2026-07-28 08:41:09.769512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '540c5f408063'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_author_id', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_authors_normalized_name', 'authors', ['normalized_name'], unique=False)
    op.create_index('uq_authors_source_author_id', 'authors', ['source', 'source_author_id'], unique=True, postgresql_where=sa.text('source IS NOT NULL AND source_author_id IS NOT NULL'))
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('taxonomy_source', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taxonomy_source', 'code', name='uq_categories_source_code')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('records_processed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_updated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_runs_job_status_started', 'ingestion_runs', ['job_type', 'status', 'started_at'], unique=False)
    op.create_table('institutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_institution_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_institution_id', name='uq_institutions_source_id')
    )
    op.create_table('publication_venues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_venue_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('venue_type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_publication_venues_source_id', 'publication_venues', ['source', 'source_venue_id'], unique=True, postgresql_where=sa.text('source IS NOT NULL AND source_venue_id IS NOT NULL'))
    op.create_table('ingestion_failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_identifier', sa.Text(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_failures_resolved', 'ingestion_failures', ['resolved'], unique=False)
    op.create_index('ix_ingestion_failures_run_id', 'ingestion_failures', ['ingestion_run_id'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('arxiv_id', sa.Text(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('normalized_title', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('primary_category_id', sa.UUID(), nullable=False),
    sa.Column('first_observed_source', sa.Text(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_version_number', sa.Integer(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['primary_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arxiv_id'),
    sa.UniqueConstraint('doi')
    )
    op.create_index('ix_papers_first_observed_at', 'papers', ['first_observed_at'], unique=False)
    op.create_index('ix_papers_normalized_title', 'papers', ['normalized_title'], unique=False)
    op.create_index('ix_papers_primary_category_id', 'papers', ['primary_category_id'], unique=False)
    op.create_table('paper_author_institutions',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'author_id', 'institution_id')
    )
    op.create_index('ix_paper_author_institutions_paper_id', 'paper_author_institutions', ['paper_id'], unique=False)
    op.create_table('paper_authors',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.Column('affiliation_text_raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'author_id'),
    sa.UniqueConstraint('paper_id', 'author_order', name='uq_paper_authors_paper_order')
    )
    op.create_index('ix_paper_authors_author_id', 'paper_authors', ['author_id'], unique=False)
    op.create_table('paper_categories',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'category_id')
    )
    op.create_index('ix_paper_categories_category_id', 'paper_categories', ['category_id'], unique=False)
    op.create_index('uq_paper_categories_one_primary_per_paper', 'paper_categories', ['paper_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_table('paper_metric_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'metric_type', 'source', 'snapshot_date', name='uq_paper_metric_snapshots_key')
    )
    op.create_index('ix_paper_metric_snapshots_lookup', 'paper_metric_snapshots', ['paper_id', 'metric_type', 'snapshot_date'], unique=False)
    op.create_table('paper_source_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_paper_id', sa.Text(), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_paper_id', name='uq_paper_source_records_source_id')
    )
    op.create_index('ix_paper_source_records_paper_id', 'paper_source_records', ['paper_id'], unique=False)
    op.create_table('paper_venues',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['publication_venues.id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'venue_id')
    )
    op.create_table('paper_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_identifier', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'version_number', name='uq_paper_versions_paper_version')
    )
    op.create_index('ix_paper_versions_paper_id', 'paper_versions', ['paper_id'], unique=False)
    op.create_index('uq_paper_versions_one_latest_per_paper', 'paper_versions', ['paper_id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_paper_versions_one_latest_per_paper', table_name='paper_versions', postgresql_where=sa.text('is_latest = true'))
    op.drop_index('ix_paper_versions_paper_id', table_name='paper_versions')
    op.drop_table('paper_versions')
    op.drop_table('paper_venues')
    op.drop_index('ix_paper_source_records_paper_id', table_name='paper_source_records')
    op.drop_table('paper_source_records')
    op.drop_index('ix_paper_metric_snapshots_lookup', table_name='paper_metric_snapshots')
    op.drop_table('paper_metric_snapshots')
    op.drop_index('uq_paper_categories_one_primary_per_paper', table_name='paper_categories', postgresql_where=sa.text('is_primary = true'))
    op.drop_index('ix_paper_categories_category_id', table_name='paper_categories')
    op.drop_table('paper_categories')
    op.drop_index('ix_paper_authors_author_id', table_name='paper_authors')
    op.drop_table('paper_authors')
    op.drop_index('ix_paper_author_institutions_paper_id', table_name='paper_author_institutions')
    op.drop_table('paper_author_institutions')
    op.drop_index('ix_papers_primary_category_id', table_name='papers')
    op.drop_index('ix_papers_normalized_title', table_name='papers')
    op.drop_index('ix_papers_first_observed_at', table_name='papers')
    op.drop_table('papers')
    op.drop_index('ix_ingestion_failures_run_id', table_name='ingestion_failures')
    op.drop_index('ix_ingestion_failures_resolved', table_name='ingestion_failures')
    op.drop_table('ingestion_failures')
    op.drop_index('uq_publication_venues_source_id', table_name='publication_venues', postgresql_where=sa.text('source IS NOT NULL AND source_venue_id IS NOT NULL'))
    op.drop_table('publication_venues')
    op.drop_table('institutions')
    op.drop_index('ix_ingestion_runs_job_status_started', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('categories')
    op.drop_index('uq_authors_source_author_id', table_name='authors', postgresql_where=sa.text('source IS NOT NULL AND source_author_id IS NOT NULL'))
    op.drop_index('ix_authors_normalized_name', table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
