"""add trend analysis tables

Revision ID: 6e0681b31044
Revises: 04d1988e2686
Create Date: 2026-07-30 22:55:34.252733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e0681b31044'
down_revision: Union[str, None] = '04d1988e2686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calculation_version', sa.Text(), nullable=False),
    sa.Column('requested_trend_mode', sa.Text(), nullable=False),
    sa.Column('effective_trend_mode', sa.Text(), nullable=False),
    sa.Column('freshness_status', sa.Text(), nullable=False),
    sa.Column('corpus_latest_publication_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recent_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recent_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comparison_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comparison_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_granularity', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_canonical_papers', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'RUNNING'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trend_analysis_runs_status_created', 'trend_analysis_runs', ['status', 'created_at'], unique=False)
    op.create_table('trend_entity_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trend_run_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('entity_name', sa.Text(), nullable=False),
    sa.Column('recent_paper_count', sa.Integer(), nullable=False),
    sa.Column('previous_paper_count', sa.Integer(), nullable=False),
    sa.Column('absolute_growth', sa.Integer(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('is_new_activity', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('recent_publication_share', sa.Float(), nullable=True),
    sa.Column('previous_publication_share', sa.Float(), nullable=True),
    sa.Column('share_change', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Boolean(), nullable=True),
    sa.Column('consistency', sa.Float(), nullable=True),
    sa.Column('recency_score', sa.Float(), nullable=True),
    sa.Column('total_papers', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trend_run_id'], ['trend_analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trend_run_id', 'entity_type', 'entity_id', name='uq_trend_entity_snapshots_run_entity')
    )
    op.create_index('ix_trend_entity_snapshots_entity', 'trend_entity_snapshots', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_trend_entity_snapshots_run_entity', 'trend_entity_snapshots', ['trend_run_id', 'entity_type', 'entity_id'], unique=False)
    op.create_table('trend_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trend_run_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('trend_type', sa.Text(), nullable=False),
    sa.Column('trend_score', sa.Integer(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('trend_classification', sa.Text(), nullable=False),
    sa.Column('data_quality_level', sa.Text(), nullable=False),
    sa.Column('component_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_explanation', sa.Text(), nullable=True),
    sa.Column('explanation_model', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('trend_score >= 0 AND trend_score <= 100', name='ck_trend_scores_score_range'),
    sa.ForeignKeyConstraint(['trend_run_id'], ['trend_analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trend_run_id', 'entity_type', 'entity_id', 'trend_type', name='uq_trend_scores_run_entity_type')
    )
    op.create_index('ix_trend_scores_classification', 'trend_scores', ['trend_classification'], unique=False)
    op.create_index('ix_trend_scores_run_type', 'trend_scores', ['trend_run_id', 'trend_type'], unique=False)
    op.create_table('trend_evidence_papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trend_score_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('recent_period', 'comparison_period')", name='ck_trend_evidence_papers_role'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['trend_score_id'], ['trend_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trend_score_id', 'paper_id', 'role', name='uq_trend_evidence_papers_score_paper_role')
    )
    op.create_index('ix_trend_evidence_papers_paper', 'trend_evidence_papers', ['paper_id'], unique=False)
    op.create_index('ix_trend_evidence_papers_score', 'trend_evidence_papers', ['trend_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trend_evidence_papers_score', table_name='trend_evidence_papers')
    op.drop_index('ix_trend_evidence_papers_paper', table_name='trend_evidence_papers')
    op.drop_table('trend_evidence_papers')
    op.drop_index('ix_trend_scores_run_type', table_name='trend_scores')
    op.drop_index('ix_trend_scores_classification', table_name='trend_scores')
    op.drop_table('trend_scores')
    op.drop_index('ix_trend_entity_snapshots_run_entity', table_name='trend_entity_snapshots')
    op.drop_index('ix_trend_entity_snapshots_entity', table_name='trend_entity_snapshots')
    op.drop_table('trend_entity_snapshots')
    op.drop_index('ix_trend_analysis_runs_status_created', table_name='trend_analysis_runs')
    op.drop_table('trend_analysis_runs')
    # ### end Alembic commands ###
