"""add clustering runs and paper cluster assignments

Revision ID: 7d721ff30378
Revises: ec0c20a951ea
Create Date: 2026-07-30 08:36:08.690014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d721ff30378'
down_revision: Union[str, None] = 'ec0c20a951ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clustering_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('embedding_model', sa.Text(), nullable=False),
    sa.Column('embedding_model_version', sa.Text(), nullable=False),
    sa.Column('algorithm_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('paper_count', sa.Integer(), nullable=False),
    sa.Column('cluster_count', sa.Integer(), nullable=False),
    sa.Column('noise_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'RUNNING'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_cluster_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clustering_run_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('membership_probability', sa.Float(), nullable=False),
    sa.Column('is_noise', sa.Boolean(), nullable=False),
    sa.Column('umap_coordinates', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT is_noise OR cluster_id IS NULL', name='ck_paper_cluster_assignments_noise_has_null_cluster'),
    sa.CheckConstraint('is_noise OR cluster_id IS NOT NULL', name='ck_paper_cluster_assignments_non_noise_has_cluster'),
    sa.CheckConstraint('membership_probability >= 0 AND membership_probability <= 1', name='ck_paper_cluster_assignments_probability_range'),
    sa.ForeignKeyConstraint(['clustering_run_id'], ['clustering_runs.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clustering_run_id', 'paper_id', name='uq_paper_cluster_assignments_run_paper')
    )
    op.create_index('ix_paper_cluster_assignments_run_cluster', 'paper_cluster_assignments', ['clustering_run_id', 'cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paper_cluster_assignments_run_cluster', table_name='paper_cluster_assignments')
    op.drop_table('paper_cluster_assignments')
    op.drop_table('clustering_runs')
    # ### end Alembic commands ###
