"""add openalex enrichment support

Revision ID: 8a3960027258
Revises: f7d9bb59df3a
Create Date: 2026-07-28 17:48:58.687598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a3960027258'
down_revision: Union[str, None] = 'f7d9bb59df3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_enrichment_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('match_status', sa.Text(), nullable=False),
    sa.Column('match_method', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched_external_id', sa.Text(), nullable=True),
    sa.Column('matching_rule_version', sa.Text(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'source', name='uq_paper_enrichment_matches_paper_source')
    )
    op.create_index('ix_paper_enrichment_matches_status', 'paper_enrichment_matches', ['match_status'], unique=False)
    op.create_table('paper_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citing_paper_id', sa.UUID(), nullable=False),
    sa.Column('cited_paper_id', sa.UUID(), nullable=True),
    sa.Column('cited_external_doi', sa.Text(), nullable=True),
    sa.Column('cited_external_openalex_id', sa.Text(), nullable=True),
    sa.Column('cited_external_arxiv_id', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cited_paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['citing_paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_references_cited_paper_id', 'paper_references', ['cited_paper_id'], unique=False)
    op.create_index('ix_paper_references_citing_paper_id', 'paper_references', ['citing_paper_id'], unique=False)
    op.create_index('uq_paper_references_citing_source_openalex_id', 'paper_references', ['citing_paper_id', 'source', 'cited_external_openalex_id'], unique=True, postgresql_where=sa.text('cited_external_openalex_id IS NOT NULL'))
    op.add_column('authors', sa.Column('identity_status', sa.Text(), server_default=sa.text("'UNRESOLVED'"), nullable=False))
    op.add_column('authors', sa.Column('identity_confidence', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'identity_confidence')
    op.drop_column('authors', 'identity_status')
    op.drop_index('uq_paper_references_citing_source_openalex_id', table_name='paper_references', postgresql_where=sa.text('cited_external_openalex_id IS NOT NULL'))
    op.drop_index('ix_paper_references_citing_paper_id', table_name='paper_references')
    op.drop_index('ix_paper_references_cited_paper_id', table_name='paper_references')
    op.drop_table('paper_references')
    op.drop_index('ix_paper_enrichment_matches_status', table_name='paper_enrichment_matches')
    op.drop_table('paper_enrichment_matches')
    # ### end Alembic commands ###
