"""add paper embeddings table

Revision ID: ec0c20a951ea
Revises: eca3c638d6f9
Create Date: 2026-07-29 12:15:29.251489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ec0c20a951ea'
down_revision: Union[str, None] = 'eca3c638d6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # vector extension was already created manually during pgvector infra
    # prep (2026-07-29); IF NOT EXISTS makes this migration re-runnable on
    # a fresh database that doesn't have that manual step behind it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('embedding_model', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('source_text_hash', sa.Text(), nullable=False),
    sa.Column('embedding_status', sa.Text(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("embedding_status <> 'SUCCEEDED' OR embedding IS NOT NULL", name='ck_paper_embeddings_succeeded_has_vector'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'embedding_model', 'model_version', name='uq_paper_embeddings_paper_model_version')
    )
    op.create_index('ix_paper_embeddings_status', 'paper_embeddings', ['embedding_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paper_embeddings_status', table_name='paper_embeddings')
    op.drop_table('paper_embeddings')
    # ### end Alembic commands ###
    # vector extension intentionally NOT dropped -- it's shared infra, not
    # owned by this migration, and dropping it here would break any other
    # feature that starts depending on it later.
