"""add source record identity history and enrichment queue

Revision ID: eca3c638d6f9
Revises: 8a3960027258
Create Date: 2026-07-29 06:48:06.498632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eca3c638d6f9'
down_revision: Union[str, None] = '8a3960027258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('contributing_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_fields', sa.Text(), server_default=sa.text("'identity_only'"), nullable=False),
    sa.Column('rule_version', sa.Text(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'source', name='uq_enrichment_queue_paper_source')
    )
    op.create_index('ix_enrichment_queue_next_retry_at', 'enrichment_queue', ['next_retry_at'], unique=False)
    op.create_index('ix_enrichment_queue_status_priority', 'enrichment_queue', ['status', 'priority'], unique=False)
    op.create_table('paper_source_record_identifier_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_source_record_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('old_source_paper_id', sa.Text(), nullable=False),
    sa.Column('new_source_paper_id', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['paper_source_record_id'], ['paper_source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_source_record_identifier_history_paper_source', 'paper_source_record_identifier_history', ['paper_id', 'source'], unique=False)
    op.create_index('ix_paper_source_record_identifier_history_record_id', 'paper_source_record_identifier_history', ['paper_source_record_id'], unique=False)
    # ### end Alembic commands ###

    # --- Data cleanup: consolidate any pre-existing (paper_id, source)
    # duplicates in paper_source_records before the new UNIQUE(paper_id,
    # source) constraint below would otherwise fail to apply. For each
    # duplicate group, the most-recently-fetched row is kept; every other
    # row's identifier is preserved in paper_source_record_identifier_history
    # (old_source_paper_id = the row being removed, new_source_paper_id =
    # the surviving row's id) before being deleted. This is general-purpose
    # (handles any duplicate group found, not just the one already known
    # about), so it also protects against duplicates this migration wasn't
    # specifically written to fix.
    op.execute("""
        WITH ranked AS (
            SELECT id, paper_id, source, source_paper_id, fetched_at,
                   row_number() OVER (
                       PARTITION BY paper_id, source
                       ORDER BY fetched_at DESC, id DESC
                   ) AS rn
            FROM paper_source_records
        ),
        keepers AS (
            SELECT paper_id, source, id AS keeper_id, source_paper_id AS keeper_source_paper_id
            FROM ranked WHERE rn = 1
        ),
        losers AS (
            SELECT r.id AS loser_id, r.paper_id, r.source, r.source_paper_id AS loser_source_paper_id
            FROM ranked r WHERE r.rn > 1
        )
        INSERT INTO paper_source_record_identifier_history
            (id, paper_source_record_id, paper_id, source, old_source_paper_id, new_source_paper_id, changed_at, reason)
        SELECT
            gen_random_uuid(),
            k.keeper_id,
            l.paper_id,
            l.source,
            l.loser_source_paper_id,
            k.keeper_source_paper_id,
            now(),
            'pre_fix_duplicate_consolidation'
        FROM losers l
        JOIN keepers k ON k.paper_id = l.paper_id AND k.source = l.source
    """)

    op.execute("""
        DELETE FROM paper_source_records
        WHERE id IN (
            SELECT id FROM (
                SELECT id, row_number() OVER (
                    PARTITION BY paper_id, source
                    ORDER BY fetched_at DESC, id DESC
                ) AS rn
                FROM paper_source_records
            ) sub
            WHERE rn > 1
        )
    """)

    op.create_unique_constraint('uq_paper_source_records_paper_source', 'paper_source_records', ['paper_id', 'source'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_paper_source_records_paper_source', 'paper_source_records', type_='unique')
    op.drop_index('ix_paper_source_record_identifier_history_record_id', table_name='paper_source_record_identifier_history')
    op.drop_index('ix_paper_source_record_identifier_history_paper_source', table_name='paper_source_record_identifier_history')
    op.drop_table('paper_source_record_identifier_history')
    op.drop_index('ix_enrichment_queue_status_priority', table_name='enrichment_queue')
    op.drop_index('ix_enrichment_queue_next_retry_at', table_name='enrichment_queue')
    op.drop_table('enrichment_queue')
    # ### end Alembic commands ###
