"""add pacing backfill and quota tables

Revision ID: f7d9bb59df3a
Revises: 540c5f408063
Create Date: 2026-07-28 11:39:51.293620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7d9bb59df3a'
down_revision: Union[str, None] = '540c5f408063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request_states',
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('last_request_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_allowed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('backfill_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_granularity', sa.Text(), nullable=False),
    sa.Column('estimated_result_count', sa.Integer(), nullable=True),
    sa.Column('page_size', sa.Integer(), nullable=False),
    sa.Column('next_page_offset', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_committed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'PLANNED'"), nullable=False),
    sa.Column('split_from_window_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['split_from_window_id'], ['backfill_windows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backfill_windows_status', 'backfill_windows', ['status'], unique=False)
    op.create_index('ix_backfill_windows_window_start', 'backfill_windows', ['window_start'], unique=False)
    op.create_table('ingestion_quota_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quota_limit', sa.Integer(), nullable=False),
    sa.Column('new_papers_available', sa.Integer(), nullable=True),
    sa.Column('historical_papers_available', sa.Integer(), nullable=True),
    sa.Column('new_papers_selected', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('historical_papers_selected', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('papers_processed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('papers_failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unused_capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'RUNNING'"), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_quota_periods_status', 'ingestion_quota_periods', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingestion_quota_periods_status', table_name='ingestion_quota_periods')
    op.drop_table('ingestion_quota_periods')
    op.drop_index('ix_backfill_windows_window_start', table_name='backfill_windows')
    op.drop_index('ix_backfill_windows_status', table_name='backfill_windows')
    op.drop_table('backfill_windows')
    op.drop_table('api_request_states')
    # ### end Alembic commands ###
